### PR TITLE
Add scripts

### PR DESCRIPTION
**Pull request by ghjbvvgh**

### CODE REVIEW

**Comment by mintygingy** [comment]
bestie, what should button do

**Comment by ghjbvvgh** [comment]
> bestie, what should button do

do what you want

**Comment by mintygingy** [comment]
and where have u got clone lua from?

**Comment by ghjbvvgh** [comment]
> and where have u got clone lua from?
i wrote it  myself

**Comment by mintygingy** [comment]
update readme also

**Pull request merged**
